theme = "solarized-dark"

[icons]
name = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
format = "{icon} {alias}:{used}/{total}"

[[block]]
block = "disk_space"
path = "/mnt/evo-pro"
alias = "evo-pro"
format = "{icon} {alias}:{used}/{total}"

[[block]]
block = "cpu"
interval = 5
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "load"
interval = 10
format = "{1m} {5m} {15m}"

[[block]]
block = "memory"
display_type = "memory"
clickable = false

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {ip} {signal_strength}"

[[block]]
block = "sound"

[[block]]
block = "temperature"
collapsed = false 
interval = 10
format = "CPU: {average}"
chip = "k10temp-pci-00c3"

[[block]]
block = "time"
interval = 60
format = "%FT%T"
timezone = "Europe/Rome"
